# -*- coding: utf-8 -*-
"""Deep Q-Learning Stock Trading Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCDKrSrAOBgWTid4qslM6gXpf_erSFuq
"""

!pip install yfinance
import yfinance as yf
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import random
from collections import deque

symbol = "AAPL"
start_date = "2020-01-01"
end_date = "2025-02-14"

# Download Historical data
data = yf.download(symbol, start=start_date, end=end_date)
display(data.head())
display(data.shape)
display(data.info())

# Feature Engineering

data["SMA_5"] = data["Close"].rolling(window=5).mean()
data["SMA_20"] = data["Close"].rolling(window=5).mean()
data["Returns"] = data["Close"].pct_change()

display(data.head())
display(data.shape)
display(data.info())

# Drop all the null values
data.dropna(inplace=True)
data.reset_index(drop=True, inplace=True)
display(data.head())
display(data.shape)

# define action space
ACTIONS = {0: "Hold", 1: "Buy", 2: "Sell"}

# extract state from the data
# get state function

# def get_state(data, index):
#   return np.array([
#                    float(data.iloc[index, 'Close']),
#                    float(data.iloc[index, 'SMA_5']),
#                    float(data.iloc[index, 'SMA_20']),
#                    float(data.iloc[index, 'Returns'])
#                    ])

def get_state(data, index):
    return np.array([
        data.iloc[index, data.columns.get_loc('Close')],  # Correct positional access
        data.iloc[index, data.columns.get_loc('SMA_5')],
        data.iloc[index, data.columns.get_loc('SMA_20')],
        data.iloc[index, data.columns.get_loc('Returns')]
    ], dtype=np.float32)

# build trading environment for our AI Agent
# define a trading environment to interact with the deep Q-Network(DQN) AI agent

class trading_environment:
  def __init__(self, data):
    self.data = data
    self.initial_balance = 10000
    self.balance = self.initial_balance
    self.holdings = 0
    self.index = 0

  def reset(self):
    self.balance = self.initial_balance
    self.holdings = 0
    self.index = 0
    return get_state(self.data, self.index)

  def step(self, action):
        price = float(self.data.iloc[self.index]['Close'])
        reward = 0

        if action == 1 and self.balance >= price:
            self.holdings = self.balance // price
            self.balance -= self.holdings * price
        elif action == 2 and self.holdings > 0:
            self.balance += self.holdings * price
            self.holdings = 0

        self.index += 1
        done = self.index >= len(self.data)
        if done:
            reward = self.balance - self.initial_balance
            next_state = np.zeros(4)  # or handle as appropriate
        else:
            next_state = get_state(self.data, self.index)

        return next_state, reward, done, {}

# deep q network(DQN)
class DQN(nn.Module):
  def __init__(self, state_size, action_size):
    super(DQN, self).__init__()
    self.fc1 = nn.Linear(state_size, 64)
    self.fc2 = nn.Linear(64, 64)
    self.fc3 = nn.Linear(64, action_size)

  def forward(self, x):
    # Reshape the input tensor to have the correct dimensions
    x = x.view(x.size(0), -1)  # Reshape to (batch_size, state_size)

    x = torch.relu(self.fc1(x))
    x = torch.relu(self.fc2(x))
    return self.fc3(x)

# dqn agent
class DQNAgent:
  def __init__(self, state_size, action_size):
    self.state_size = state_size
    self.action_size = action_size
    self.memory = deque(maxlen=2000)
    self.gamma = 0.95
    self.epsilon = 1.0
    self.epsilon_decay = 0.995
    self.epsilon_min = 0.01
    self.learning_rate = 0.001
    self.model = DQN(state_size, action_size)
    self.optimizer = optim.Adam(self.model.parameters(), lr=self.learning_rate)
    self.criterion = nn.MSELoss()

  def remember(self, state, action, reward, next_state, done):
    self.memory.append((state, action, reward, next_state, done))

  def act(self, state):
    if random.uniform(0, 1) <= self.epsilon:
      # return random.choice(list(ACTIONS.keys()))
      return random.randrange(self.action_size)
    state = torch.FloatTensor(state).unsqueeze(0)
    with torch.no_grad():
      q_values = self.model(state)
    return torch.argmax(q_values).item()

  def replay(self, batch_size):
    if len(self.memory) < batch_size:
      return
    minibatch = random.sample(self.memory, batch_size)

    for state, action, reward, next_state, done in minibatch:
      target = reward
      if not done:
        # Reshape next_state to ensure it has the correct dimensions
        # next_state = torch.FloatTensor(next_state).unsqueeze(0)
        next_state = torch.tensor(next_state, dtype=torch.float32).unsqueeze(0) # Modified line: Ensures next_state is a float tensor and adds a dimension for the batch size.
        target = reward + self.gamma * torch.max(self.model(next_state)).item()

      # state_tensor = torch.FloatTensor(state).unsqueeze(0)
      state_tensor = torch.tensor(state, dtype=torch.float32).unsqueeze(0) # Modified line: Ensures state is a float tensor and adds a dimension for the batch size.
      target_tensor = self.model(state_tensor).clone().detach()
      target_tensor[0][action] = target

      self.optimizer.zero_grad()
      output = self.model(state_tensor)
      loss = self.criterion(output, target_tensor)
      loss.backward()
      self.optimizer.step()

    if self.epsilon > self.epsilon_min:
      self.epsilon *= self.epsilon_decay

# Train the agent

env = trading_environment(data)
agent = DQNAgent(state_size = 4, action_size = 3)
batch_size = 32
episodes = 100
total_rewards = []

for episode in range(episodes):
  state = env.reset()
  done = False
  total_reward = 0

  while not done:
    action = agent.act(state)
    next_state, reward, done, _ = env.step(action)
    agent.remember(state, action, reward, next_state, done)
    state = next_state
    total_reward += reward

  agent.replay(batch_size)
  total_rewards.append(total_reward)
  print(f"Episode: {episode+1}/{episodes}, Total Reward: {total_reward}")
print("Training Complete")

# create a fresh environment instance for testing

test_env = trading_environment(data)
state = test_env.reset()
done = False

# simulate a trading session using the trained agents
while not done:
  # always choose the best action (exploitation)
  action = agent.act(state)
  next_state, reward, done, _ = test_env.step(action)
  state = next_state if next_state is not None else state
  print(f"Action: {ACTIONS[action]}, Reward: {reward}")

final_balance = test_env.balance
profit = final_balance - test_env.initial_balance
print(f"Final Balance after testing: ${final_balance:.2f}")
print(f"Total profit: ${profit:.2f}")

